name: RankReminder
version: ${project.version}
main: pl.r3craft.rankreminder.RankReminder
authors: [ r3cord ]
description: Plugin that reminds players to buy rank for longer.
website: r3craft.pl

commands:
  Ranga:
    aliases: [rankexpiration]
    description: Shows when player's rank expires
    usage: /<command>
  rankreminder:

depend: [LuckPerms]